services:
  mastra-express:
    build: .
    env_file:
      - docker.env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: always
  db:
    image: pgvector/pgvector:pg16
    container_name: celent_ai_db
    env_file:
      - docker.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6699:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata: